02/03/2021 01:09:55|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 01:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 01:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 01:09:55|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/03/2021 01:41:22|INFO    |root                            |Provider opensubtitles throttle count 1 of 5, waiting 5sec and trying again|
02/03/2021 01:41:42|INFO    |root                            |Provider opensubtitles throttle count 2 of 5, waiting 5sec and trying again|
02/03/2021 01:41:47|INFO    |root                            |Provider opensubtitles throttle count 3 of 5, waiting 5sec and trying again|
02/03/2021 01:42:05|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 01:52, because of: KeyError. Exception info: 'season'|
02/03/2021 01:42:12|WARNING |retry.api                       |HTTPSConnectionPool(host='www.podnapisi.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
02/03/2021 01:42:23|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 01:52, because of: KeyError. Exception info: 'season'|
02/03/2021 01:42:29|WARNING |retry.api                       |HTTPSConnectionPool(host='www.podnapisi.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
02/03/2021 01:43:00|WARNING |retry.api                       |HTTPSConnectionPool(host='www.podnapisi.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
02/03/2021 01:43:06|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
02/03/2021 04:00:01|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
02/03/2021 04:09:55|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 04:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 04:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 04:09:55|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/03/2021 04:41:52|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 04:51, because of: KeyError. Exception info: 'season'|
02/03/2021 04:41:54|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 04:51, because of: KeyError. Exception info: 'season'|
02/03/2021 04:42:00|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
02/03/2021 05:00:01|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
02/03/2021 06:41:32|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 06:43:40|INFO    |root                            |BAZARR Running cache maintenance|
02/03/2021 07:06:55|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 07:16, because of: KeyError. Exception info: 'season'|
02/03/2021 07:07:27|INFO    |root                            |BAZARR Finished searching for Subtitles to upgrade. Check History for more information.|
02/03/2021 07:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 07:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 07:09:55|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/03/2021 07:41:21|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 07:41:48|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 07:51, because of: KeyError. Exception info: 'season'|
02/03/2021 07:41:53|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 07:51, because of: KeyError. Exception info: 'season'|
02/03/2021 07:42:02|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
02/03/2021 10:09:55|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 10:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 10:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 10:09:55|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/03/2021 10:41:33|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 10:51, because of: KeyError. Exception info: 'season'|
02/03/2021 10:41:38|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 10:51, because of: KeyError. Exception info: 'season'|
02/03/2021 10:41:53|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
02/03/2021 13:09:55|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 13:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 13:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 13:09:55|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/03/2021 13:42:15|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 13:52, because of: KeyError. Exception info: 'season'|
02/03/2021 13:42:17|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 13:52, because of: KeyError. Exception info: 'season'|
02/03/2021 13:42:31|WARNING |retry.api                       |HTTPSConnectionPool(host='www.podnapisi.net', port=443): Max retries exceeded with url: /subtitles/search/old?sXML=1&sL=en&sK=alone&sTS=2&sTE=13 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3bf26da970>: Failed to establish a new connection: [Errno -3] Try again')), retrying in 5 seconds...|
02/03/2021 13:42:39|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
02/03/2021 16:09:55|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 16:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 16:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 16:09:55|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/03/2021 16:41:56|WARNING |retry.api                       |HTTPSConnectionPool(host='www.sous-titres.eu', port=443): Max retries exceeded with url: /search.html?q=The+Amazing+Race (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3bf2a6a0a0>: Failed to establish a new connection: [Errno -3] Try again')), retrying in 5 seconds...|
02/03/2021 16:42:05|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 16:52, because of: KeyError. Exception info: 'season'|
02/03/2021 16:42:11|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 16:52, because of: KeyError. Exception info: 'season'|
02/03/2021 16:42:17|WARNING |retry.api                       |HTTPSConnectionPool(host='www.podnapisi.net', port=443): Max retries exceeded with url: /subtitles/search/old?sXML=1&sL=fr&sK=alone&sTS=2&sTE=12 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3bf2fb5730>: Failed to establish a new connection: [Errno -3] Try again')), retrying in 5 seconds...|
02/03/2021 16:42:37|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
02/03/2021 19:06:51|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 19:06:55|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 19:16, because of: KeyError. Exception info: 'season'|
02/03/2021 19:07:15|INFO    |root                            |BAZARR Finished searching for Subtitles to upgrade. Check History for more information.|
02/03/2021 19:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 19:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 19:09:55|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/03/2021 19:41:21|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 19:41:57|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 19:51, because of: KeyError. Exception info: 'season'|
02/03/2021 19:42:04|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 19:52, because of: KeyError. Exception info: 'season'|
02/03/2021 19:42:12|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
02/03/2021 21:46:32|INFO    |root                            |Using soustitreseu again after 10 minutes, (disabled because: KeyError)|
02/03/2021 22:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 22:09:55|ERROR   |root                            |BAZARR Error trying to get video information for this file: /data/media/movies/The Avengers (2012)/The Avengers (2012) BR-DISK.iso|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/get_subtitle.py", line 62, in get_video\n    video = parse_video(path, hints=hints, providers=providers, dry_run=used_scene_name,\n  File "/app/bazarr/bazarr/../libs/subzero/video.py", line 61, in parse_video\n    return scan_video(fn, hints=hints, dont_use_actual_file=dry_run, providers=providers,\n  File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 504, in scan_video\n    raise ValueError(\'%r is not a valid video extension\' % os.path.splitext(path)[1])\nValueError: \'.iso\' is not a valid video extension'|
02/03/2021 22:09:55|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/03/2021 22:42:15|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 22:52, because of: KeyError. Exception info: 'season'|
02/03/2021 22:42:20|INFO    |root                            |Throttling soustitreseu for 10 minutes, until 21/03/02 22:52, because of: KeyError. Exception info: 'season'|
02/03/2021 22:42:37|INFO    |root                            |BAZARR Finished searching for missing Series Subtitles. Check History for more information.|
